# Generated by Django 5.0.3 on 2024-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvideo',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
